# Generated by Django 4.2.5 on 2024-01-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_alter_email_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
