# Generated by Django 4.2.5 on 2024-01-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_email_checkbox_checked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='checkbox_checked',
            new_name='important',
        ),
        migrations.RemoveField(
            model_name='email',
            name='labels',
        ),
    ]
